import { makeVar } from '@apollo/client'

export const current_value_menu = makeVar()
export const current_parent_id_menu = makeVar()
export const current_parent_value_menu = makeVar()
export const current_id_menu = makeVar()
export const current_created_menu = makeVar()
export const current_updated_menu = makeVar()

export const current_value_catalog = makeVar()
export const current_parent_id_catalog = makeVar()
export const current_parent_value_catalog = makeVar()
export const current_id_catalog = makeVar()
export const current_created_catalog = makeVar()
export const current_updated_catalog = makeVar()

export const current_value_rubric = makeVar()
export const current_parent_id_rubric = makeVar()
export const current_parent_value_rubric = makeVar()
export const current_id_rubric = makeVar()
export const current_created_rubric = makeVar()
export const current_updated_rubric = makeVar()

export const current_title_category = makeVar()
export const current_seoDescription_category = makeVar()
export const current_value_category = makeVar()
export const current_parent_id_category = makeVar()
export const current_parent_value_category = makeVar()
export const current_id_category = makeVar()
export const current_created_category = makeVar()
export const current_updated_category = makeVar()

export const current_value_product = makeVar()
export const current_value_product_price = makeVar()
export const current_id_product_price = makeVar()
export const current_value_product_unit = makeVar()
export const current_parent_id_product = makeVar()
export const current_parent_value_product = makeVar()
export const current_id_product = makeVar()
export const current_created_product = makeVar()
export const current_updated_product = makeVar()
